// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA6vQz411-f4DELkhlKVOAPrSPxS5FAzBI',
    appId: '1:396534485647:web:e10c04f1016ca3fa2896fa',
    messagingSenderId: '396534485647',
    projectId: 'todo-app-ac4ff',
    authDomain: 'todo-app-ac4ff.firebaseapp.com',
    storageBucket: 'todo-app-ac4ff.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBuFD9vjPtJ1eczLHdCLA_TwMw3HHXpwHw',
    appId: '1:396534485647:android:33686c0cf1ef23b52896fa',
    messagingSenderId: '396534485647',
    projectId: 'todo-app-ac4ff',
    storageBucket: 'todo-app-ac4ff.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCrh93jtDdgMmu2kKx7MbiwCIXODPuOI6w',
    appId: '1:396534485647:ios:9895039edc4f9bda2896fa',
    messagingSenderId: '396534485647',
    projectId: 'todo-app-ac4ff',
    storageBucket: 'todo-app-ac4ff.appspot.com',
    iosClientId: '396534485647-bjn7kb9c9qge5jap68veqsobf0bpmgap.apps.googleusercontent.com',
    iosBundleId: 'com.example.todoapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCrh93jtDdgMmu2kKx7MbiwCIXODPuOI6w',
    appId: '1:396534485647:ios:9895039edc4f9bda2896fa',
    messagingSenderId: '396534485647',
    projectId: 'todo-app-ac4ff',
    storageBucket: 'todo-app-ac4ff.appspot.com',
    iosClientId: '396534485647-bjn7kb9c9qge5jap68veqsobf0bpmgap.apps.googleusercontent.com',
    iosBundleId: 'com.example.todoapp',
  );
}
